name: Node PR CI
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NAME: supertape
      FORCE_COLOR: 3
    strategy:
      matrix:
        node-version:
          - 16.x
          - 18.x
          - 20.x
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Redrun
        run: npm i redrun -g
      - name: Install
        run: npm install
      - name: Bootstrap
        run: redrun bootstrap
      - name: Lint
        run: redrun lint
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Typos Install
        run: cargo install typos-cli || echo 'already installed'
      - name: Typos
        run: typos
      - name: Coverage
        run: redrun coverage report
